### ISSUE TITLE
ACL2021中的ACOS开源的代码怎么找不到？

### ISSUE THREAD

**Issue by Heart-beatsss** [NUSTM/ABSA-Reading-List#1]
你们删掉了吗？什么时候再次开源？

**Comment by blhoy** [comment]
> 你们删掉了吗？什么时候再次开源？

正在对数据和代码作最后的整理，近期将发布出来。请保持对我们github的关注。谢谢！

**Comment by blhoy** [comment]
> 你们删掉了吗？什么时候再次开源？

你好，数据和代码已发布：https://github.com/NUSTM/ACOS

**Comment by Heart-beatsss** [comment]
好的，非常感谢！
